---
- hosts: all
  become: true
  tasks:
    - name: Update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Update repository index
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip
  
  - name: install terraform
    unarchive:
      src: https://go.nagios.org/get-core/4-4-13
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: CentOS_servers
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip
  
  - name: install terraform
    unarchive:
      src: https://go.nagios.org/get-core/4-4-13
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
