---
- name: Install epel-relaese
  yum: name=epel-release state=present

- name: Install required packages
  yum:
    name:
      - nagios
      - nagios-plugins-all
      - openssl
      - nrpe
      - nagios-plugins-nrpe
    state: present

- name: start nagios
  service: name={{item}} state=restarted enabled=yes
  with_items:
    - httpd
    - nagios

